package com.projectmgmt.domain.activity;

public enum ActivityType {
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_TRANSITIONED,
    ISSUE_ASSIGNED,
    ISSUE_DELETED,
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    SPRINT_CREATED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    SPRINT_UPDATED,
    ISSUE_MOVED_TO_SPRINT,
    ISSUE_MOVED_TO_BACKLOG,
    WATCHER_ADDED,
    WATCHER_REMOVED
}
